version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    command: mongod

  backend:
    container_name: backend
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: backend_dockerfile
    restart: always
    ports:
      - "80:80"